# app.rb
require 'sinatra'
require 'mysql2'
require 'sinatra/activerecord'
require 'digest'
require 'openssl'
require 'base64'
require 'chunky_png'
require_relative 'routes/main'
require_relative 'routes/index'
require_relative 'routes/auth'
require_relative 'models'
require_relative 'script/reverse'
require_relative 'script/algoritma_aes'
require_relative 'script/steganodriver'

set :database_file, 'database.yml'